mongo setup

diff --git a/HW3/makefile b/HW3/makefile
--- a/HW3/makefile
+++ b/HW3/makefile
@@ -1,10 +1,23 @@
 .SILENT:
 
-run:
-	if [ -z "$(q)" ]; then \
-		echo "Error: q is not set"; \
-		exit 1; \
-	fi; 
-	saxonb-xquery -s ./congress.xml $(q).xq > $(q).xml
+	run:
+		if [ -z "$(q)" ]; then \
+			echo "Error: q is not set"; \
+			exit 1; \
+		fi; 
 
-.PHONY: run
+		touch xmloutput/$(q).xml
+
+		saxonb-xquery -s ./congress.xml $(q).xq > xmloutput/$(q).xml
+
+	restore:
+		if [ -z "$(q)" ]; then \
+			echo "Error: q is not set"; \
+			exit 1; \
+		fi; 
+
+		touch output/$(q).out
+
+		mongosh ${MONGODB_URL}congress?authSource=admin --quiet -f $(q).js > output/$(q).out
+
+.PHONY: run restore
